# Ad Service with Health Check Issues
# This manifest enables health check failure simulation

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
    demo-issue: health-check-failures
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: adservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: adservice
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        - name: DISABLE_PROFILER
          value: "1"
        # Health check failure simulation configuration
        - name: SIMULATE_HEALTH_CHECK_FAILURES
          value: "true"
        - name: HEALTH_CHECK_FAILURE_RATE
          value: "0.25"  # 25% chance of failure every interval
        - name: HEALTH_CHECK_INTERVAL_SECONDS
          value: "20"    # Check every 20 seconds
        - name: HEALTH_CHECK_FAILURE_DURATION_SECONDS
          value: "15"    # Failure lasts 15 seconds
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 9555
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 9555
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice