# Recommendation Service with Issue Simulation via Sidecar
# Uses a lightweight sidecar container to simulate memory/CPU issues
# without modifying the main application image

apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
    demo-issue: sidecar-simulation
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      serviceAccountName: recommendationservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      # Main application container (unchanged)
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.8.0
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: 8080
        livenessProbe:
          periodSeconds: 5
          grpc:
            port: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: DISABLE_PROFILER
          value: "1"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

      # Issue simulation sidecar
      - name: issue-simulator
        image: busybox:1.36
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Starting issue simulator..."
          
          # Memory leak simulation
          if [ "$ENABLE_MEMORY_LEAK" = "true" ]; then
            echo "Simulating memory leak..."
            while true; do
              # Allocate memory gradually
              dd if=/dev/zero of=/tmp/leak-$(date +%s) bs=1M count=10 2>/dev/null || true
              sleep 5
            done &
          fi
          
          # CPU spike simulation  
          if [ "$SIMULATE_CPU_SPIKES" = "true" ]; then
            echo "Simulating CPU spikes..."
            while true; do
              # Create CPU load for 10 seconds every 30 seconds
              timeout 10s dd if=/dev/zero of=/dev/null bs=1M 2>/dev/null || true
              sleep 20
            done &
          fi
          
          # Keep container running
          while true; do sleep 3600; done
        env:
        - name: ENABLE_MEMORY_LEAK
          value: "true"  # Set to "false" to disable
        - name: SIMULATE_CPU_SPIKES
          value: "false" # Set to "true" to enable
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 150Mi
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendationservice